from .personaView import PersonaListView, PersonaRetrieveUpdateDeleteView
from .medicoView import MedicoListCreateView, MedicoRetrieveUpdateView
from .pacienteView import PacienteListCreateView, PacienteRetrieveUpdateView