# Generated by Django 3.2.15 on 2022-09-23 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=15, unique=True, verbose_name='Usuario')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.BigAutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=60, verbose_name='Direccion')),
                ('correo', models.CharField(max_length=60, verbose_name='Correo')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=30, verbose_name='Especialidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('latitud', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Longitud')),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='homeCareApp.familiar')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='homeCareApp.medico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_signos', models.BigAutoField(primary_key=True, serialize=False)),
                ('oximetria', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Oximetria')),
                ('frecuenciaRespiratoria', models.IntegerField(verbose_name='Frecuencia Respiratoria')),
                ('frecuenciaCardiaca', models.IntegerField(verbose_name='Frecuencia Cardiaca')),
                ('temperatura', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Temperatura')),
                ('presionArterial', models.IntegerField(verbose_name='Presion Arterial')),
                ('glicemia', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Glicemia')),
                ('fecha', models.DateField()),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signosvitales', to='homeCareApp.familiar')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signosvitales', to='homeCareApp.paciente')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signosvitales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_has_medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_has_medico', to='homeCareApp.familiar')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_has_medico', to='homeCareApp.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_has_medico', to='homeCareApp.paciente')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_has_medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historia', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('motivoConsulta', models.CharField(max_length=60, verbose_name='Motivo Consulta')),
                ('enfermedades', models.CharField(max_length=60, verbose_name='Enfermedades')),
                ('antecedentes', models.CharField(max_length=60, verbose_name='Antecedentes')),
                ('diagnostico', models.CharField(max_length=60, verbose_name='Diagnostico')),
                ('sugerenciasCuidados', models.CharField(max_length=60, verbose_name='Sugerencias Cuidados')),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaclinica', to='homeCareApp.familiar')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaclinica', to='homeCareApp.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaclinica', to='homeCareApp.paciente')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaclinica', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id_enfermero', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
