# Generated by Django 3.2.15 on 2022-09-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipousuario',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Tipousuario'),
        ),
    ]
