# Generated by Django 3.2.15 on 2022-10-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.CharField(default=None, max_length=20, verbose_name='Rol'),
            preserve_default=False,
        ),
    ]
