# Generated by Django 3.2.15 on 2022-10-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0002_persona_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='id_medico',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_paciente',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
